POST https://todo-app-lzp7.onrender.com/api/item
Content-Type: application/json

{
  "item": "This is the second todo item"
}

###

GET https://todo-app-lzp7.onrender.com/api/items
Content-Type: application/json

###

PUT https://todo-app-lzp7.onrender.com/api/item/6245bfd3eb7b72345090f275
Content-Type: application/json

{
  "item": "This is the second todo item updated!!"
}

###

DELETE  https://todo-app-lzp7.onrender.com/api/item/6245bad3eb7b72345090f273
Content-Type: application/json
